version: '3.8'
services:
  app:
    build: ./demo
    ports:
      - "8081:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Lac_Viec_BookStore
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0901178334bin
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    restart: unless-stopped

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: Lac_Viec_BookStore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0901178334bin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:

