spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: bookstore
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}
    expiration-ms: ${JWT_EXPIRATION_MS}
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /
