package com.example.demo.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.Data;

import java.util.Set;

/**
 * Data Transfer Object for User
 */
@Data
public class UserDto {
    private Long id;

    @NotBlank(message = "Username is required")
    @Size(min = 3, max = 50, message = "Username must be between 3 and 50 characters")
    @Pattern(regexp = "^[a-zA-Z0-9_]+$", message = "Username can only contain letters, numbers and underscores")
    private String username;

    @NotBlank(message = "Email is required")
    @Email(message = "Email should be valid")
    private String email;

    @Size(min = 6, max = 100, message = "Password must be between 6 and 100 characters")
    private String password;

    @NotBlank(message = "Full name is required")
    private String fullName;

    private String phone;
    
    private boolean enabled = true;
    
    private Set<String> roles;
    
    // Getters and Setters are generated by Lombok @Data
    
    /**
     * Check if the user has admin role
     */
    public boolean isAdmin() {
        return roles != null && roles.contains("ROLE_ADMIN");
    }
    
    /**
     * Check if the user has user role
     */
    public boolean isUser() {
        return roles != null && roles.contains("ROLE_USER");
    }
}
